import { Company } from '@/types';

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'c001',
    name: 'OpenAI',
    website: 'https://openai.com',
    logo: 'https://logo.clearbit.com/openai.com',
    tagline: 'AI research and deployment for AGI benefit',
    description: 'OpenAI is an AI research company building safe and beneficial artificial general intelligence. Their flagship products — ChatGPT, GPT-4, and the API — are used by millions of developers and enterprises worldwide for text, code, image, and voice generation.',
    stage: 'Series A',
    sector: 'AI / LLM',
    subSectors: ['AI/ML', 'Enterprise SaaS'],
    founded: 2015,
    headcount: 1800,
    location: 'San Francisco, CA',
    country: 'USA',
    funding: {
      total: 11300000000,
      lastRound: 10000000000,
      lastRoundType: 'Series A',
      lastRoundDate: '2024-03-01',
    },
    founders: [
      { name: 'Sam Altman', role: 'CEO', linkedin: 'https://linkedin.com/in/samaltman', previousCompany: 'Y Combinator' },
      { name: 'Greg Brockman', role: 'President', linkedin: '#', previousCompany: 'Stripe' },
    ],
    thesisScore: 98,
    thesisReasons: ['Market leader in AI/LLM space', 'Massive enterprise adoption', 'Strong API moat and developer ecosystem'],
    signals: [
      { date: '2024-06-01', type: 'funding', title: 'Raised $10B from Microsoft', source: 'TechCrunch' },
      { date: '2024-05-15', type: 'product', title: 'Launched GPT-4o with voice mode', source: 'OpenAI Blog' },
      { date: '2024-04-20', type: 'hiring', title: 'Posting 200+ engineering roles', source: 'LinkedIn' },
    ],
    tags: ['AI', 'LLM', 'B2B', 'SaaS'],
    status: 'watching',
    notes: 'Top priority — track API pricing changes and enterprise tier.',
    enriched: false,
    createdAt: '2024-01-10',
  },
  {
    id: 'c002',
    name: 'Stripe',
    website: 'https://stripe.com',
    logo: 'https://logo.clearbit.com/stripe.com',
    tagline: 'Financial infrastructure for the internet',
    description: 'Stripe builds economic infrastructure for the internet. Businesses of every size use Stripe to accept payments, send payouts, and manage their businesses online. Stripe powers millions of companies including Amazon, Google, Salesforce and Shopify.',
    stage: 'Series A',
    sector: 'Fintech',
    subSectors: ['Payments', 'B2B SaaS'],
    founded: 2010,
    headcount: 8000,
    location: 'San Francisco, CA',
    country: 'USA',
    funding: {
      total: 8700000000,
      lastRound: 6500000000,
      lastRoundType: 'Series A',
      lastRoundDate: '2023-03-15',
    },
    founders: [
      { name: 'Patrick Collison', role: 'CEO', linkedin: '#', previousCompany: 'Auctomatic' },
      { name: 'John Collison', role: 'President', linkedin: '#', previousCompany: 'Auctomatic' },
    ],
    thesisScore: 95,
    thesisReasons: ['Dominant payments infrastructure', 'Strong developer-first GTM', 'Expanding into financial services'],
    signals: [
      { date: '2024-05-28', type: 'product', title: 'Launched Stripe Tax globally', source: 'Stripe Blog' },
      { date: '2024-04-10', type: 'partnership', title: 'Deepened AWS partnership for global payments', source: 'Press Release' },
    ],
    tags: ['Fintech', 'Payments', 'B2B', 'SaaS'],
    status: 'contacted',
    notes: 'Met Patrick at SaaStr. Incredible GTM motion — studying their developer docs strategy.',
    enriched: false,
    createdAt: '2024-02-14',
  },
  {
    id: 'c003',
    name: 'Notion',
    website: 'https://notion.so',
    logo: 'https://logo.clearbit.com/notion.so',
    tagline: 'One workspace. Every team.',
    description: 'Notion is an all-in-one workspace for notes, docs, wikis, and project management. With the launch of Notion AI, it has become a major AI-native productivity platform used by over 30 million people and 50% of Fortune 500 companies.',
    stage: 'Series B',
    sector: 'Productivity SaaS',
    subSectors: ['AI/ML', 'Collaboration'],
    founded: 2016,
    headcount: 500,
    location: 'San Francisco, CA',
    country: 'USA',
    funding: {
      total: 343000000,
      lastRound: 275000000,
      lastRoundType: 'Series B',
      lastRoundDate: '2021-10-08',
    },
    founders: [
      { name: 'Ivan Zhao', role: 'CEO', linkedin: '#', previousCompany: 'Freelance' },
      { name: 'Simon Last', role: 'CTO', linkedin: '#', previousCompany: 'Freelance' },
    ],
    thesisScore: 88,
    thesisReasons: ['AI-native pivot strengthening moat', 'Strong PLG with enterprise upsell', 'Deep workflow integration stickiness'],
    signals: [
      { date: '2024-06-05', type: 'product', title: 'Notion AI launched Q&A over entire workspace', source: 'ProductHunt' },
      { date: '2024-05-01', type: 'hiring', title: 'Scaling enterprise sales team', source: 'LinkedIn' },
    ],
    tags: ['Productivity', 'AI', 'B2B', 'SaaS', 'PLG'],
    status: 'new',
    notes: '',
    enriched: false,
    createdAt: '2024-03-01',
  },
  {
    id: 'c004',
    name: 'Vercel',
    website: 'https://vercel.com',
    logo: 'https://logo.clearbit.com/vercel.com',
    tagline: 'Build and deploy the best web experiences',
    description: 'Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration. Vercel enables teams to iterate faster by providing an out-of-the-box toolchain to ship, iterate, and scale.',
    stage: 'Series C',
    sector: 'Developer Tools',
    subSectors: ['Cloud Infrastructure', 'Frontend'],
    founded: 2015,
    headcount: 1000,
    location: 'San Francisco, CA',
    country: 'USA',
    funding: {
      total: 313000000,
      lastRound: 150000000,
      lastRoundType: 'Series C',
      lastRoundDate: '2022-05-23',
    },
    founders: [
      { name: 'Guillermo Rauch', role: 'CEO', linkedin: '#', previousCompany: 'LearnBoost' },
    ],
    thesisScore: 91,
    thesisReasons: ['Dominant in frontend deployment market', 'Next.js gives deep ecosystem lock-in', 'AI-accelerated development workflow'],
    signals: [
      { date: '2024-06-02', type: 'product', title: 'Vercel AI SDK v3 launched', source: 'Vercel Blog' },
      { date: '2024-05-10', type: 'partnership', title: 'Expanded partnership with AWS', source: 'Press Release' },
    ],
    tags: ['DevTools', 'Cloud', 'Frontend', 'B2B', 'SaaS'],
    status: 'watching',
    notes: 'Next.js moat is enormous. Watch Series D timing.',
    enriched: false,
    createdAt: '2024-04-15',
  },
  {
    id: 'c005',
    name: 'Anthropic',
    website: 'https://anthropic.com',
    logo: 'https://logo.clearbit.com/anthropic.com',
    tagline: 'AI safety company building reliable, interpretable AI',
    description: 'Anthropic is an AI safety company working to build reliable, interpretable, and steerable AI systems. Their Claude models are used by enterprises for coding, analysis, writing, and complex reasoning — with a strong focus on safety and helpfulness.',
    stage: 'Series B',
    sector: 'AI / LLM',
    subSectors: ['AI Safety', 'Enterprise SaaS'],
    founded: 2021,
    headcount: 700,
    location: 'San Francisco, CA',
    country: 'USA',
    funding: {
      total: 7300000000,
      lastRound: 4000000000,
      lastRoundType: 'Series B',
      lastRoundDate: '2024-04-10',
    },
    founders: [
      { name: 'Dario Amodei', role: 'CEO', linkedin: '#', previousCompany: 'OpenAI' },
      { name: 'Daniela Amodei', role: 'President', linkedin: '#', previousCompany: 'OpenAI' },
    ],
    thesisScore: 96,
    thesisReasons: ['Safety-first positioning resonates with regulated enterprises', 'Claude 3 benchmarks beating GPT-4', 'Amazon partnership gives major distribution'],
    signals: [
      { date: '2024-06-08', type: 'product', title: 'Claude 3.5 Sonnet released — outperforms GPT-4o', source: 'Anthropic Blog' },
      { date: '2024-05-22', type: 'funding', title: '$4B raised from Google and others', source: 'WSJ' },
      { date: '2024-04-30', type: 'partnership', title: 'Amazon Bedrock integration deepened', source: 'AWS Blog' },
    ],
    tags: ['AI', 'LLM', 'Safety', 'B2B', 'Enterprise'],
    status: 'watching',
    notes: 'Closest OpenAI competitor. Track enterprise pricing.',
    enriched: false,
    createdAt: '2024-02-28',
  },
  {
    id: 'c006',
    name: 'Linear',
    website: 'https://linear.app',
    logo: 'https://logo.clearbit.com/linear.app',
    tagline: 'The issue tracker built for high-performance teams',
    description: 'Linear is a streamlined project management tool for software teams. Known for its blazing speed and opinionated workflow, Linear has become the default issue tracker for top startups — and is now expanding with AI-powered planning features.',
    stage: 'Series B',
    sector: 'Developer Tools',
    subSectors: ['Project Management', 'B2B SaaS'],
    founded: 2019,
    headcount: 100,
    location: 'San Francisco, CA',
    country: 'USA',
    funding: {
      total: 52000000,
      lastRound: 35000000,
      lastRoundType: 'Series B',
      lastRoundDate: '2022-03-14',
    },
    founders: [
      { name: 'Karri Saarinen', role: 'CEO', linkedin: '#', previousCompany: 'Coinbase' },
      { name: 'Jori Lallo', role: 'CTO', linkedin: '#', previousCompany: 'Coinbase' },
    ],
    thesisScore: 85,
    thesisReasons: ['Strong brand loyalty among engineers', 'Efficient team — high revenue per employee', 'AI roadmap is compelling'],
    signals: [
      { date: '2024-06-02', type: 'product', title: 'Linear AI auto-triage launched', source: 'Linear Blog' },
      { date: '2024-05-10', type: 'hiring', title: 'First enterprise sales hires', source: 'LinkedIn' },
    ],
    tags: ['DevTools', 'Project Management', 'B2B', 'SaaS'],
    status: 'new',
    notes: '',
    enriched: false,
    createdAt: '2024-04-15',
  },
  {
    id: 'c007',
    name: 'Figma',
    website: 'https://figma.com',
    logo: 'https://logo.clearbit.com/figma.com',
    tagline: 'The collaborative design platform for teams',
    description: 'Figma is a browser-based collaborative design tool used by over 4 million people. It has become the standard for product design teams and is now expanding into AI-powered design generation and developer handoff workflows.',
    stage: 'Series D',
    sector: 'Design SaaS',
    subSectors: ['Collaboration', 'AI/ML'],
    founded: 2012,
    headcount: 1400,
    location: 'San Francisco, CA',
    country: 'USA',
    funding: {
      total: 700000000,
      lastRound: 200000000,
      lastRoundType: 'Series D',
      lastRoundDate: '2021-06-24',
    },
    founders: [
      { name: 'Dylan Field', role: 'CEO', linkedin: '#', previousCompany: 'Flipboard' },
      { name: 'Evan Wallace', role: 'CTO', linkedin: '#', previousCompany: 'Brown University' },
    ],
    thesisScore: 82,
    thesisReasons: ['Design-to-dev workflow becoming more valuable', 'AI generation features gaining traction', 'Strong enterprise penetration'],
    signals: [
      { date: '2024-06-07', type: 'product', title: 'Figma AI design generation launched at Config 2024', source: 'Figma Blog' },
      { date: '2024-05-18', type: 'hiring', title: 'Building out AI team aggressively', source: 'LinkedIn' },
    ],
    tags: ['Design', 'AI', 'SaaS', 'Collaboration', 'B2B'],
    status: 'new',
    notes: '',
    enriched: false,
    createdAt: '2024-05-20',
  },
  {
    id: 'c008',
    name: 'Hugging Face',
    website: 'https://huggingface.co',
    logo: 'https://logo.clearbit.com/huggingface.co',
    tagline: 'The AI community platform for models and datasets',
    description: 'Hugging Face is the GitHub of AI — an open-source platform for machine learning models, datasets, and demos. With over 500,000 models hosted and deep enterprise integrations, it has become critical infrastructure for every AI team.',
    stage: 'Series C',
    sector: 'AI Infrastructure',
    subSectors: ['AI/ML', 'Developer Tools', 'Open Source'],
    founded: 2016,
    headcount: 350,
    location: 'New York, NY',
    country: 'USA',
    funding: {
      total: 395000000,
      lastRound: 235000000,
      lastRoundType: 'Series C',
      lastRoundDate: '2023-08-24',
    },
    founders: [
      { name: 'Clément Delangue', role: 'CEO', linkedin: '#', previousCompany: 'Moodstocks' },
      { name: 'Julien Chaumond', role: 'CTO', linkedin: '#', previousCompany: 'Moodstocks' },
    ],
    thesisScore: 93,
    thesisReasons: ['Critical AI infrastructure with massive network effects', 'Open-source community gives unbeatable distribution', 'Enterprise tier growing rapidly'],
    signals: [
      { date: '2024-05-30', type: 'product', title: 'Launched Inference Endpoints for enterprise', source: 'HF Blog' },
      { date: '2024-03-22', type: 'partnership', title: 'Google Cloud partnership for model hosting', source: 'Google Blog' },
    ],
    tags: ['AI', 'ML', 'Open Source', 'Infrastructure', 'B2B'],
    status: 'watching',
    notes: 'GitHub of AI — essential infrastructure. Monitor enterprise tier growth.',
    enriched: false,
    createdAt: '2024-01-25',
  },
];
